-- Run this in the Supabase Dashboard SQL Editor for the Quickstart sample.

create table if not exists public.scores (
    id bigint generated by default as identity primary key,
    player_name text not null unique,
    score integer not null default 0
);

alter table public.scores enable row level security;
grant select on table public.scores to anon, authenticated;

do $$
begin
    if not exists (
        select 1
        from pg_policies
        where schemaname = 'public'
          and tablename = 'scores'
          and policyname = 'Quickstart scores are readable'
    ) then
        create policy "Quickstart scores are readable"
            on public.scores
            for select
            to anon, authenticated
            using (true);
    end if;
end
$$;

insert into public.scores (player_name, score)
values
    ('Ada', 1200),
    ('Grace', 950),
    ('Linus', 800)
on conflict (player_name) do nothing;

do $$
begin
    if exists (
        select 1 from pg_publication where pubname = 'supabase_realtime'
    ) and not exists (
        select 1
        from pg_publication_tables
        where pubname = 'supabase_realtime'
          and schemaname = 'public'
          and tablename = 'scores'
    ) then
        execute 'alter publication supabase_realtime add table public.scores';
    end if;
end
$$;
