using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json.Linq;
using UnityEditor;
using UnityEngine;
using UnityEngine.Networking;

namespace Supabase.Unity.Editor
{
    internal sealed class SupabaseModelGeneratorWindow : EditorWindow
    {
        private const string GeneratedMarker = "// <auto-generated by Supabase for Unity />";
        private static readonly HashSet<string> CSharpKeywords = new HashSet<string>(StringComparer.Ordinal)
        {
            "abstract", "as", "base", "bool", "break", "byte", "case", "catch", "char", "checked",
            "class", "const", "continue", "decimal", "default", "delegate", "do", "double", "else",
            "enum", "event", "explicit", "extern", "false", "finally", "fixed", "float", "for",
            "foreach", "goto", "if", "implicit", "in", "int", "interface", "internal", "is", "lock",
            "long", "namespace", "new", "null", "object", "operator", "out", "override", "params",
            "private", "protected", "public", "readonly", "ref", "return", "sbyte", "sealed", "short",
            "sizeof", "stackalloc", "static", "string", "struct", "switch", "this", "throw", "true",
            "try", "typeof", "uint", "ulong", "unchecked", "unsafe", "ushort", "using", "virtual",
            "void", "volatile", "while"
        };
        private string projectUrl = string.Empty;
        private string publishableKey = string.Empty;
        private string secretApiKey = string.Empty;
        private string outputFolder = "Assets/Supabase/Generated";
        private string generatedNamespace = "Game.Database";
        private string status = "Fetches the Data API OpenAPI schema and creates plain C# models.";
        private string settingsSourcePath;
        private bool allowCustomSchemaHost;
        private bool generating;

        [MenuItem("Tools/Supabase/Model Generator")]
        private static void Open()
        {
            GetWindow<SupabaseModelGeneratorWindow>("Supabase Models");
        }

        private void OnEnable()
        {
            LoadFromSupabaseSettings(false);
        }

        private void OnGUI()
        {
            EditorGUILayout.HelpBox(
                "Supabase requires a secret API key to read the OpenAPI schema. The secret is kept only in this Editor window and is never written to SupabaseSettings or generated files. Never use it in a player build.",
                MessageType.Warning);
            projectUrl = EditorGUILayout.TextField("Project URL", projectUrl);
            publishableKey = EditorGUILayout.PasswordField("Runtime Publishable Key", publishableKey);
            secretApiKey = EditorGUILayout.PasswordField("Secret API Key (Editor only)", secretApiKey);
            allowCustomSchemaHost = EditorGUILayout.Toggle("Allow Custom Schema Host", allowCustomSchemaHost);
            if (allowCustomSchemaHost)
                EditorGUILayout.HelpBox(
                    "The Editor-only secret will be sent to the configured custom/self-hosted Project URL. Enable this only after verifying the host.",
                    MessageType.Warning);
            if (!string.IsNullOrEmpty(settingsSourcePath))
                EditorGUILayout.LabelField("Settings", settingsSourcePath, EditorStyles.miniLabel);
            outputFolder = EditorGUILayout.TextField("Output Folder", outputFolder);
            generatedNamespace = EditorGUILayout.TextField("Namespace", generatedNamespace);
            EditorGUI.BeginDisabledGroup(generating);
            if (GUILayout.Button("Reload from SupabaseSettings"))
                LoadFromSupabaseSettings(true);
            if (GUILayout.Button(generating ? "Generating..." : "Fetch Schema and Generate"))
                GenerateAsync();
            EditorGUI.EndDisabledGroup();
            EditorGUILayout.Space();
            EditorGUILayout.HelpBox(status, status.StartsWith("Error", StringComparison.Ordinal) ? MessageType.Error : MessageType.None);
        }

        private void OnDisable()
        {
            // Avoid serializing or retaining an elevated key with the Editor window.
            secretApiKey = string.Empty;
        }

        private bool LoadFromSupabaseSettings(bool overwriteExisting)
        {
            var settings = Selection.activeObject as SupabaseSettings;
            var path = settings == null ? null : AssetDatabase.GetAssetPath(settings);
            if (settings == null)
            {
                var guids = AssetDatabase.FindAssets("t:SupabaseSettings");
                var paths = new string[guids.Length];
                for (var index = 0; index < guids.Length; index++)
                    paths[index] = AssetDatabase.GUIDToAssetPath(guids[index]);
                Array.Sort(paths, StringComparer.OrdinalIgnoreCase);
                if (paths.Length > 0)
                {
                    path = paths[0];
                    settings = AssetDatabase.LoadAssetAtPath<SupabaseSettings>(path);
                }
            }

            if (settings == null)
            {
                if (overwriteExisting)
                    status = "Error: No SupabaseSettings asset was found in the project.";
                settingsSourcePath = null;
                Repaint();
                return false;
            }

            if (overwriteExisting || string.IsNullOrWhiteSpace(projectUrl))
                projectUrl = settings.ProjectUrl;
            if (overwriteExisting || string.IsNullOrWhiteSpace(publishableKey))
                publishableKey = settings.PublishableKey;
            settingsSourcePath = path;
            status = "Loaded Supabase configuration from " + path + ".";
            Repaint();
            return true;
        }

        private async void GenerateAsync()
        {
            generating = true;
            status = "Validating configuration...";
            Repaint();
            try
            {
                var databaseEndpoint = ResolveDatabaseEndpoint(projectUrl, allowCustomSchemaHost);
                ValidateEditorSecretKey(secretApiKey);
                var editorSecret = secretApiKey.Trim();
                string openApiText;
                using (var request = UnityWebRequest.Get(databaseEndpoint.AbsoluteUri.TrimEnd('/') + "/"))
                {
                    request.timeout = 30;
                    request.redirectLimit = 0;
                    request.SetRequestHeader("apikey", editorSecret);
                    request.SetRequestHeader("Accept", "application/openapi+json");
                    var operation = request.SendWebRequest();
                    while (!operation.isDone) await Task.Delay(25);
#if UNITY_2020_2_OR_NEWER
                    if (request.result != UnityWebRequest.Result.Success)
#else
                    if (request.isNetworkError || request.isHttpError)
#endif
                        throw new InvalidOperationException(SupabaseHttp.Redact(
                            request.error + "\n" + request.downloadHandler.text));
                    openApiText = request.downloadHandler.text;
                }

                var openApi = JObject.Parse(openApiText);
                var schemas = openApi["definitions"] as JObject ?? openApi["components"]?["schemas"] as JObject;
                if (schemas == null || !schemas.HasValues)
                    throw new InvalidOperationException("The OpenAPI document did not contain table schemas. Check Data API exposure and grants.");

                var absoluteFolder = ResolveOutputFolder(outputFolder);
                generatedNamespace = ValidateNamespace(generatedNamespace);
                var generatedFiles = new List<KeyValuePair<string, string>>();
                var destinations = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
                foreach (var schema in schemas.Properties())
                {
                    var definition = schema.Value as JObject;
                    if (definition == null || definition["properties"] == null) continue;
                    var className = Identifier(schema.Name, true);
                    var destination = Path.Combine(absoluteFolder, className + ".cs");
                    if (!destinations.Add(destination))
                        throw new InvalidOperationException(
                            "Multiple schema definitions map to the generated type " + className + ". Rename the conflicting database objects.");
                    EnsureSafeGeneratedTarget(destination);
                    generatedFiles.Add(new KeyValuePair<string, string>(destination,
                        GenerateModel(schema.Name, className, definition, generatedNamespace)));
                }
                Directory.CreateDirectory(absoluteFolder);
                foreach (var generatedFile in generatedFiles)
                    File.WriteAllText(generatedFile.Key, generatedFile.Value, new UTF8Encoding(false));
                AssetDatabase.Refresh();
                status = "Generated " + generatedFiles.Count + " model(s) in " + outputFolder + ".";
            }
            catch (Exception exception)
            {
                status = "Error: " + SupabaseHttp.Redact(exception.Message);
            }
            finally
            {
                secretApiKey = string.Empty;
                generating = false;
                Repaint();
            }
        }

        internal static string ResolveOutputFolder(string configuredFolder)
        {
            if (string.IsNullOrWhiteSpace(configuredFolder))
                throw new InvalidOperationException("Output Folder cannot be empty.");
            var assetsRoot = Path.GetFullPath(Application.dataPath)
                .TrimEnd(Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar);
            var projectRoot = Directory.GetParent(assetsRoot).FullName;
            var absoluteFolder = Path.GetFullPath(Path.Combine(projectRoot, configuredFolder));
            var assetsPrefix = assetsRoot + Path.DirectorySeparatorChar;
            if (!string.Equals(absoluteFolder, assetsRoot, StringComparison.OrdinalIgnoreCase) &&
                !absoluteFolder.StartsWith(assetsPrefix, StringComparison.OrdinalIgnoreCase))
                throw new InvalidOperationException("Output Folder must resolve inside this project's Assets directory.");
            return absoluteFolder;
        }

        private static void EnsureSafeGeneratedTarget(string path)
        {
            if (!File.Exists(path))
                return;
            using (var reader = new StreamReader(path, Encoding.UTF8, true))
            {
                if (!string.Equals(reader.ReadLine(), GeneratedMarker, StringComparison.Ordinal))
                    throw new InvalidOperationException(
                        "Refusing to overwrite a file that was not created by this generator: " + path);
            }
        }

        internal static string ValidateNamespace(string value)
        {
            value = string.IsNullOrWhiteSpace(value) ? "Game.Database" : value.Trim();
            var parts = value.Split('.');
            foreach (var part in parts)
            {
                if (string.IsNullOrEmpty(part) || CSharpKeywords.Contains(part) ||
                    !(char.IsLetter(part[0]) || part[0] == '_'))
                    throw new InvalidOperationException("Namespace contains an invalid C# identifier: " + value);
                for (var index = 1; index < part.Length; index++)
                    if (!(char.IsLetterOrDigit(part[index]) || part[index] == '_'))
                        throw new InvalidOperationException("Namespace contains an invalid C# identifier: " + value);
            }
            return value;
        }

        internal static Uri ResolveDatabaseEndpoint(string url, bool allowCustomHost = false)
        {
            Uri projectUri;
            if (!Uri.TryCreate(url, UriKind.Absolute, out projectUri) ||
                (projectUri.Scheme != Uri.UriSchemeHttps && projectUri.Scheme != Uri.UriSchemeHttp))
                throw new InvalidOperationException("Project URL must be an absolute HTTP or HTTPS URL.");
            if (!string.IsNullOrEmpty(projectUri.UserInfo) || !string.IsNullOrEmpty(projectUri.Query) ||
                !string.IsNullOrEmpty(projectUri.Fragment))
                throw new InvalidOperationException(
                    "Project URL cannot contain user credentials, a query string, or a fragment.");
            var isLocal = projectUri.IsLoopback || string.Equals(projectUri.Host, "localhost",
                StringComparison.OrdinalIgnoreCase);
            if (projectUri.Scheme != Uri.UriSchemeHttps && !isLocal)
                throw new InvalidOperationException("Non-local Supabase projects must use HTTPS.");
            if (!allowCustomHost && !isLocal &&
                !projectUri.Host.EndsWith(".supabase.co", StringComparison.OrdinalIgnoreCase))
                throw new InvalidOperationException(
                    "For safety, schema secrets are sent only to *.supabase.co or loopback by default. Verify the host and enable Allow Custom Schema Host for a self-hosted/custom-domain project.");
            return new Uri(projectUri.AbsoluteUri.TrimEnd('/') + "/rest/v1");
        }

        private static void ValidateEditorSecretKey(string key)
        {
            if (string.IsNullOrWhiteSpace(key))
                throw new InvalidOperationException(
                    "Enter an sb_secret_ API key from Supabase Dashboard > Settings > API Keys. It is used only for schema generation.");
            if (!key.Trim().StartsWith("sb_secret_", StringComparison.OrdinalIgnoreCase))
                throw new InvalidOperationException(
                    "The schema endpoint requires an sb_secret_ API key. Do not replace the publishable key in SupabaseSettings.");
            foreach (var character in key.Trim())
                if (!(char.IsLetterOrDigit(character) || character == '_' || character == '-'))
                    throw new InvalidOperationException("The secret API key contains invalid characters.");
        }

        internal static string GenerateModel(
            string table, string className, JObject definition, string generatedNamespace)
        {
            var required = new HashSet<string>(StringComparer.Ordinal);
            var requiredArray = definition["required"] as JArray;
            if (requiredArray != null)
                foreach (var item in requiredArray) required.Add((string)item);

            var builder = new StringBuilder();
            builder.AppendLine(GeneratedMarker);
            builder.AppendLine("using System;");
            builder.AppendLine("using System.Collections.Generic;");
            builder.AppendLine("using Newtonsoft.Json;");
            builder.AppendLine("using Supabase.Unity;");
            builder.AppendLine("using UnityEngine.Scripting;");
            builder.AppendLine();
            builder.AppendLine("namespace " + (string.IsNullOrWhiteSpace(generatedNamespace) ? "Game.Database" : generatedNamespace));
            builder.AppendLine("{");
            builder.AppendLine("    [SupabaseTable(\"" + Escape(table) + "\")]");
            builder.AppendLine("    [Preserve]");
            builder.AppendLine("    public sealed class " + className);
            builder.AppendLine("    {");
            var properties = (JObject)definition["properties"];
            foreach (var property in properties.Properties())
            {
                var schema = property.Value as JObject ?? new JObject();
                var propertyName = Identifier(property.Name, true);
                var type = CsType(schema, required.Contains(property.Name));
                builder.AppendLine("        [JsonProperty(\"" + Escape(property.Name) + "\")]");
                builder.AppendLine("        [SupabaseColumn(\"" + Escape(property.Name) + "\")]");
                builder.AppendLine("        public " + type + " " + propertyName + " { get; set; }");
                builder.AppendLine();
            }
            builder.AppendLine("    }");
            builder.AppendLine("}");
            return builder.ToString();
        }

        private static string CsType(JObject schema, bool required)
        {
            var type = (string)schema["type"];
            var format = (string)schema["format"];
            string result;
            if (type == "integer") result = format == "int64" ? "long" : "int";
            else if (type == "number") result = format == "float" ? "float" : "double";
            else if (type == "boolean") result = "bool";
            else if (type == "array") result = "List<" + CsType(schema["items"] as JObject ?? new JObject(), true) + ">";
            else if (type == "object") result = "Newtonsoft.Json.Linq.JObject";
            else if (format == "uuid") result = "Guid";
            else if (format == "date-time" || format == "timestamp with time zone") result = "DateTimeOffset";
            else if (format == "date") result = "DateTime";
            else result = "string";
            if (!required && (result == "int" || result == "long" || result == "float" || result == "double" ||
                              result == "bool" || result == "Guid" || result == "DateTime" || result == "DateTimeOffset"))
                result += "?";
            return result;
        }

        private static string Identifier(string value, bool pascal)
        {
            var builder = new StringBuilder();
            var upper = pascal;
            foreach (var character in value ?? string.Empty)
            {
                if (!char.IsLetterOrDigit(character)) { upper = true; continue; }
                var output = upper ? char.ToUpperInvariant(character) : character;
                if (builder.Length == 0 && char.IsDigit(output)) builder.Append('_');
                builder.Append(output);
                upper = false;
            }
            return builder.Length == 0 ? "Value" : builder.ToString();
        }

        private static string Escape(string value)
        {
            return (value ?? string.Empty)
                .Replace("\\", "\\\\")
                .Replace("\"", "\\\"")
                .Replace("\r", "\\r")
                .Replace("\n", "\\n")
                .Replace("\t", "\\t");
        }
    }
}
